use ocuparesali;


INSERT INTO sali VALUES(default, 0, 'AC0-1', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC0-2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC0-3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC2-1', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC2-2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'CH1', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'E1', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'E3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'A0-6', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC3-2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'AC3-3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'A1-7', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'A1-9', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'A1-13', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C0-2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C0-3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C0-4', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C0-5', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C0-6', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C1-3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C1-4', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C2-8', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C2-11', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C2-12', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C2-13', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C2-14', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C3-3', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'C4-2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'T4', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'Corp-T', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'T9', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'TV', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'CH7C', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'CH8C', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'CH2', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'M1', false, 'AMFITEATRU');
INSERT INTO sali VALUES(default, 0, 'M2', false, 'AMFITEATRU');

select * from sali;